<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-7DB4GVKK" ignored="2" name="Test5(failed)" tests="1" failures="1" timestamp="2022-09-02T19:31:57 IST" time="16.816" errors="0">
  <testcase name="testHomeCheckBox" time="5.233" classname="com.demoQA.tests.CheckBox_Test">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at com.demoQA.tests.CheckBox_Test.testHomeCheckBox(CheckBox_Test.java:38)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testHomeCheckBox -->
  <testcase name="testHomeTxt" time="0.0" classname="com.demoQA.tests.CheckBox_Test">
    <ignored/>
  </testcase> <!-- testHomeTxt -->
  <testcase name="testHeaderTxt" time="0.0" classname="com.demoQA.tests.CheckBox_Test">
    <ignored/>
  </testcase> <!-- testHeaderTxt -->
</testsuite> <!-- Test5(failed) -->
